version: '3.8'

services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - ./.env_dev
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

  flask_app:
    build: ./flask_app
    ports: 
      - '127.0.0.1:5000:5000'
    env_file:
      - ./.env_dev
    volumes:
      - ./flask_app:/flask_app
      - uploads:/uploads

  vue_app:
    build: ./vue_app
    ports: 
      - '127.0.0.1:3000:3000'
    env_file:
      - ./.env_dev
    volumes:
      - ./vue_app:/usr/src/app

  nginx:
    image: nginx
    ports: 
      - '127.0.0.1:8080:80'
    env_file:
      - ./.env_dev
    volumes:
      - ./nginx:/etc/nginx
      - uploads:/www/data/uploads
 
volumes:
  mysql_data:
  uploads:

