version: '3.8'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env_dev
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

  flask_app:
    build: ./flask_app
    ports: 
      - '5000:5000'
    env_file:
      - ./.env_dev
    volumes:
      - ./flask_app:/flask_app
      - uploads:/uploads

  nginx:
    image: nginx
    ports: 
      - '8080:80'
    env_file:
      - ./.env_dev
    volumes:
      - ./nginx_prod:/etc/nginx
      - ./vue_app/dist:/www/data/dist
      - uploads:/www/data/uploads
 
volumes:
  mysql_data:
  uploads:

